### ISSUE TITLE
Media selector for profile and attachments

### ISSUE THREAD

**Issue by ylothar** [tgalal/wazapp#168]
The problem: in preferences, or if I try to attach an image in a message, image selector idles with spinner spinning forever. I've read http://wiki.maemo.org/Wazapp#Pictures_not_Appearing_for_Selecting_Profile_Picture and applied those indications. I've  uninstalled wup, cleaned both /opt/waxmppplugin/ and /home/user/.wazapp folders, rebooted N9, reinstalled wup, rebooted again and redone my account registration. The problem I have it's still there.
I've installed latest version 0.9.12.
Let me know if I can help you with other informations. Thank you all for your wonderful job :)

**Comment by CODeRUS** [comment]
Cannot confirm. Its working for me.

**Comment by ylothar** [comment]
lol :) I've found it. Simply, I didn't have any picture on my phone :P (I've forgotten I did a full factory reset few days ago). Anyway, I think it's better that if you don't have any picture available the spinner stops and then appear something like "no image found".
Sorry for my oversight :P

**Comment by CODeRUS** [comment]
yeah, lol.

**Comment by soryuuha** [comment]
regarding image selector spinner spinning forever..i have the logs that may help to diagnose this. happen quite frequent to me. 

http://pastebin.com/4mFFV2Tf

**Comment by CODeRUS** [comment]
log says image d41d8cd98f00b204e9800998ecf8427e.jpeg broken (can't find its thumbnail) and its name similar to wazapp received image.
i see you had a problem with conversation after crashing receiving media. this maybe a cause for both issues.
i cannot suggest  anything for this unexpected trouble.

**Comment by soryuuha** [comment]
which one you meant by "problem with converstation"?

EDIT: replaced the missing image with fake image with same filename..thoroughly testing if the spinner problem rise again =)

**Comment by soryuuha** [comment]
the spinner-forever problem happened again after send media twice. not sure what's the cause this time..any advice?

http://pastebin.com/jmp1XMUA

GETTING IMAGE FILES...
Traceback (most recent call last):
  File "/opt/waxmppplugin/bin/wazapp/ui.py", line 415, in getImageFiles
    self.iface.Queue(str(url),"image/png","grid", True)
  File "/usr/lib/pymodules/python2.6/dbus/proxies.py", line 140, in **call**
    **keywords)
  File "/usr/lib/pymodules/python2.6/dbus/connection.py", line 630, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.3459 was not provided by any .service files

**Comment by CODeRUS** [comment]
i can advice you to reflash your garbage prone and install wazapp.im version.
too many impossible bugs from you.

**Comment by soryuuha** [comment]
@coderus taken ur advice, reflash my n9, ensure no wazapp related binaries anymore. Install Fresh wazapp. After A while..still get infinite spinner
