### ISSUE TITLE
Message decode error

### ISSUE THREAD

**Issue by tgalal** [tgalal/wazapp#78]
Logs indicate that most probably message affected message is in Arabic

Relevant log (see http://talk.maemo.org/showpost.php?p=1227174&postcount=1607):

libqtcontacts-tracker: initializing libqtcontacts-tracker 4.18.2-1+0m7 for /usr/bin/python2.6[2116]
CACHING
CACHED
init load convs
loading messages
find all messages
found all messages
Traceback (most recent call last):
  File "/opt/waxmppplugin/bin/wazapp/wazapp", line 37, in <module>
    wam = WAManager(app)
  File "/opt/waxmppplugin/bin/wazapp/wamanager.py", line 45, in **init**
    self.proceed()
  File "/opt/waxmppplugin/bin/wazapp/wamanager.py", line 106, in proceed
    gui.populateContacts();
  File "/opt/waxmppplugin/bin/wazapp/ui.py", line 160, in populateContacts
    self.messageStore.loadConversations()
  File "/opt/waxmppplugin/bin/wazapp/messagestore.py", line 64, in loadConversations
    self.loadMessages(c.id)
  File "/opt/waxmppplugin/bin/wazapp/messagestore.py", line 153, in loadMessages
    self.sendMessagesReady(conversation_id);
  File "/opt/waxmppplugin/bin/wazapp/messagestore.py", line 98, in sendMessagesReady
    msg['content'] = msg['content'].decode('utf-8');
  File "/usr/lib/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfa in position 318: invalid start byte

**Comment by ghost** [comment]
Log URL doesn't work.Is it that log that you sent ?

**Comment by CepiPerez** [comment]
Trying to open a media file calle josé.png I realize I can't
Then I've added this in /opt/waxmppplugin/bin/wazapp/wazapp file (before translator):

linuxCodec = QtCore.QTextCodec.codecForName("UTF-8")
QtCore.QTextCodec.setCodecForTr(linuxCodec)
QtCore.QTextCodec.setCodecForCStrings(linuxCodec)
QtCore.QTextCodec.setCodecForLocale(linuxCodec)

Now this problem is gone. Maybe it can help on your problem cause everything should use utf8 (I think)
